# Generated by Django 3.2 on 2021-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusermodel',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
