# Generated by Django 3.2 on 2021-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newusermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_pic',
            field=models.ImageField(upload_to='advisorPics/'),
        ),
    ]
